pipeline {
  agent any
  stages {
    stage('Init') {
      steps {
        sh '''cd $TERRAFORM_CONFIG_DIRECTORY

terraform init -input=false -backend-config=backend.tf
'''
      }
    }
    stage('Plan') {
      steps {
        sh '''cd $TERRAFORM_CONFIG_DIRECTORY

terraform plan -input=false -out=tfplan
'''
      }
    }
  }
}
