pipeline {
  agent any
  stages {
    stage('Init') {
      steps {
        sh '''cd $TERRAFORM_CONFIG_DIRECTORY
        
for filePath in $(git diff --name-only $GIT_PREVIOUS_COMMIT $GIT_PR_SHA)
do
  if [ "${filePath: -3}" == ".tf" ]
  then
    TERRAFORM_DIRECTORY=$(dirname "${filePath}")
    break
  fi
done
echo 'x'
echo $TERRAFORM_DIRECTORY
terraform init -input=false -backend-config=backend.tf
'''
      }
    }
    stage('Plan') {
      steps {
        sh '''cd $TERRAFORM_CONFIG_DIRECTORY

terraform plan -input=false -out=tfplan
'''
      }
    }
  }
}
