pipeline {
  agent any
  stages {
    stage('Plan') {
      steps {
        sh '''#!/bin/bash -xe
for filePath in $(git diff --name-only $GIT_PREVIOUS_COMMIT $GIT_PR_SHA)
do
  if [ ${filePath: -3} == ".tf" ]
  then
    terraformDirectory=$(dirname $filePath)
    break
  fi
done
cd $terraformDirectory
terraform init -input=false -backend-config=backend.tf
terraform plan -input=false -out=tfplan
'''
      }
    }
  }
}
