pipeline {
  agent any
  parameters {
    string(name: 'ARM_TENANT_ID', description: 'Azure Active Directory tenant identifier.')
    string(name: 'ARM_SUBSCRIPTION_ID', description: 'Azure subscription identifier.')
    booleanParam(name: 'ARM_USE_MSI', defaultValue: true, description: 'Azure managed service identity (MSI) authorization.')
    booleanParam(name: 'TF_IN_AUTOMATION', defaultValue: true, description: 'Terraform designator for orchestration context.')
  }  
  triggers {
    GenericTrigger(
      genericVariables: [
        [key: 'LABEL', value: '$.pull_request.head.label'],
        [key: 'MERGED', value: '$.pull_request.merged']
      ],
      causeString: '$LABEL',
      regexpFilterText: '$MERGED',
      regexpFilterExpression: 'true'
    )
  }
  stages {
    stage('Validate Context') {
      steps {
        copyArtifacts projectName: 'Plan', optional: true
      }
    }
    stage('Terraform Apply') {
      when {
        expression {
          fileExists('tfPlan')
        }
      }      
      steps {
        sh '''#!/bin/bash -xe
terraform apply -input=false tfPlan
'''
      }
    }
  }
}
