pipeline {
  agent any
  stages {
    stage('Apply') {
      steps {
        copyArtifacts 'Plan'
        sh '''#!/bin/bash -xe

for changedFile in $(git diff --name-only $GIT_COMMIT $GIT_PR_SHA)
do
  if [ ${changedFile: -3} == ".tf" ]
  then
    terraformDirectory=$(dirname $changedFile)
    break
  fi
done

if [ -v terraformDirectory ]
then
  cd $terraformDirectory
  terraform apply -input=false tfplan
fi
'''
      }
    }
  }
}
