pipeline {
  agent any
  stages {
    stage('Apply') {
      when {
        branch 'PR-*'
      }
      steps {
        sh '''cd $TERRAFORM_CONFIG_DIRECTORY

terraform apply -input=false tfplan
'''
      }
    }
  }
}
