pipeline {
  agent any
  stages {
    stage('Apply') {
      steps {
        step([
          $class: 'CopyArtifact',
          projectName: "Plan"
        ])
        sh '''#!/bin/bash -xe
terraform apply -input=false tfplan
'''
      }
    }
  }
}
