pipeline {
  agent any
  stages {
    stage('Plan') {
      steps {
        sh '''#!/bin/bash -xe

for changedFile in $(git diff --name-only $GIT_COMMIT $GIT_PR_SHA)
do
  if [ ${changedFile: -3} == ".tf" ]
  then
    tfConfigDirectory=$(dirname $changedFile)
    break
  fi
done

if [ -v tfConfigDirectory ]
then
  echo "$tfConfigDirectory" > tfConfig.d
  cp $TF_BACKEND_CONFIG $tfConfigDirectory
  cd $tfConfigDirectory
  terraform init -input=false -backend-config=$TF_BACKEND_CONFIG
  terraform plan -input=false -out=tfplan
fi
'''
      }
    }
  }
  post {
    success {
      when {
        fileExists('tfConfig.d')
      }
      dir(readFile('tfConfig.d').trim()) {
        archiveArtifacts '**/*'
      }
    }
  }
}
