pipeline {
  agent any
  stages {
    stage('Validate Context') {
      steps {
        sh '''#!/bin/bash -xe
for changedFile in $(git diff --name-only $GIT_COMMIT $GIT_PR_SHA)
do
  if [ ${changedFile: -3} == ".tf" ]
  then
    echo "$(dirname $changedFile)" > tfFilePath
    break
  fi
done
'''
      }
    }
    stage('Terraform Plan') {
      when {
        expression {
          fileExists('tfFilePath')
        }
      }
      steps {
        sh '''#!/bin/bash -xe
tfFilePath=$(cat tfFilePath)
cp $TF_BACKEND_CONFIG $tfFilePath
cd $tfFilePath
terraform init -input=false -backend-config=$TF_BACKEND_CONFIG
terraform plan -input=false -out=tfPlan
'''
        dir(readFile('tfFilePath')) {
          archiveArtifacts artifacts: '**/*'
        }
      }
    }
  }
}
