pipeline {
  agent any
  stages {
    stage('Plan') {
      steps {
        sh '''#!/bin/bash -xe

for changedFile in $(git diff --name-only $GIT_COMMIT $GIT_PR_SHA)
do
  if [ ${changedFile: -3} == ".tf" ]
  then
    tfFilePath=$(dirname $changedFile)
    break
  fi
done

if [ -v tfFilePath ]
then
  echo "$tfFilePath" > tfFilePath
  cp $TF_BACKEND_CONFIG $tfFilePath
  cd $tfFilePath
  terraform init -input=false -backend-config=$TF_BACKEND_CONFIG
  terraform plan -input=false -out=tfPlan
fi
'''
      }
    }
    stage('Artifact') {
      when {
        expression {
          fileExists('tfFilePath')
        }
      }
      steps {
        dir(readFile('tfFilePath').trim()) {
          archiveArtifacts artifacts: '**/*'
        }
      }
    }
  }
}
