pipeline {
  agent any
  stages {
    stage('Apply') {
      steps {
        copyArtifacts projectName: 'Plan', optional: true
        sh '''#!/bin/bash -xe
terraform apply -input=false tfPlan
'''
      }
    }
  }
}
